### ISSUE TITLE
Where is the difference between Mimic and Flite?

### ISSUE THREAD

**Issue by iUltimateLP** [MycroftAI/mimic#213]
The title basically asks it all!

**Comment by forslund** [comment]
Mimic is very similar to Flite, flite was not very actively maintained way back when we did the fork. cleaned up the source code, added an additional voice and support for PortAudio as an audio backend and added some performance improvements.

There is a [mimic-core](https://github.com/MycroftAI/mimic1-core) project that is a major architecture change. Making it all more modular.

Flite has since released (at least) one new version updating the flitevox format so there is some features for those missing

**Comment by iUltimateLP** [comment]
Thanks!
