### ISSUE TITLE
CG flitevox file compatibility

### ISSUE THREAD

**Issue by m-toman** [MycroftAI/mimic#32]
Clustergen (CG) "flitevox" files are binary dumps created by `cst_cg_dump_voice`.
This restricts compatibility with voices trained on other systems.
Endianness is checked in `cst_cg_read_header` but just throws an error instead of byte-swapping.
There is a number of uses of e.g. `sizeof(int)`, so different word sizes matter.

**Comment by zeehio** [comment]
Thanks for reporting and sorry for the delay replying.

Actually sizeof(int) and sizeof(short) are 32 an 16 bits respectively on both x86 and amd64 architectures [[1](https://wiki.debian.org/ArchitectureSpecificsMemo)]and both architectures are little endian, so maybe that's why there does not seem to be crashes.

In #56, I have replaced the uses of int and short by their respective fixed width alternatives in most input/output functions. Without  an actual hardware architecture to test on, I don't think it is a priority to review the whole code base right now, although patches are welcome.

**Comment by m-toman** [comment]
You are right, currently there are few compilers where this isn't true, so probably this isn't really an issue.
I wrote this when my voice loading crashed randomly at some point and suspected something like this to be the reason - took me some time to notice that my voice file was corrupted :).

**Comment by zeehio** [comment]
The pull request for this issue has been merged, so I close the issue. Thanks for reporting!
