### ISSUE TITLE
Add Contributing section to README.md

### ISSUE THREAD

**Issue by forslund** [MycroftAI/mimic#9]
A section should be added to the ```README.md``` detailing the development model. Should at least include
* Always create pull requests against the Development branch
* Coding style requirements

In addition commit log message style might be nice but may be pushing the bureaucracy one step too far =)

**Comment by ryanleesipes** [comment]
@forslund I think this is a good idea. "How to Contribute" 

We should also include this info on https://mimic.mycroft.ai under the Get Involved chapter.

**Comment by LongBoolean** [comment]
Good ideas, I'll get to work on it.

**Comment by zeehio** [comment]
I have found a mixture of tabs and spaces in some of mimic files. I don't mind using one coding style or another but I would rather have only one style.

I am used to indent using two spaces and using braces as follows (I just found out that this is called the [Google style](https://gist.github.com/davidzchen/9187878))

```c
int main(int argc, char **argv) {
  // code
  if (condition) {
    // code
  } else {
    //code
  }
  for (int i=0; i<4;i++) {
    if (i < 3) {
      //code
    }
  }
  return 0; // comment
}
```

Any preferences?

**Comment by forslund** [comment]
My personal inclinations are the complete opposite. I like my braces on new lines and I like to use 4 spaces as indentation. I am adaptable though and if you feel strongly about your style I'll see if I can update my vim-settings to match =)

**Comment by zeehio** [comment]
I use 4 spaces as indentation in python so to me adapting to that is not an issue. I don't mind adapting to braces. Let's wait today to see if anyone else (@longboolean) has a strong opinion on this. If everyone is happy with your style could you share your vim indentation settings or find if your style has a name easy to refer to? 

Fixing code style issues tends to generate conflicts in pull requests, the sooner we make a decision the better.

**Comment by LongBoolean** [comment]
When it comes to writing C code I prefer the following style:
```
int main(int argc, char **argv)
{
        /* code */
        if (really_long_condition &&
                another_long_condition &&
                yet_another_long_condition)
        {
                /* code */
        }
        else if (condition)
        {
                /* code */
        }
        else
        {
                /* code */
        }
        for (int i=0; i<4;i++)
        {
                if (i < 3)
                {
                        /* code */
                }
        }
        return 0; /* comment */
}
```
I am a fan of tabs and I also prefer having braces on their own line. It just reads better that way imho. Braces on their own line just visually set the code block apart from the statement above and allows you to have nice milti-line conditions(instead of them running off the side). Some languages can't have the starting brace on its own line (I'm looking at you javascript), because it is undefined behavior and causes bugs, but that is a problem with those languages. (end of rant) 

Also note if want to stay with ANSI C we will not be able to use `//` line comments. I actually like line comments a lot but ANSI C doesn't have them. (well some compilers can, but most complain)

**Comment by LongBoolean** [comment]
And as for how to write functions, I have been doing pretty much what you would expect.
```
static void DoSomethingAwesome(int SomeValue, float Percentage, custom_struct *CustomData)
{ 
       /*code*/
}
```
But I have been looking at another style:
```
static void 
DoSomethingAwesome(int SomeValue, float Percentage, custom_struct *CustomData)
{ 
       /*code*/
}
```

**Comment by LongBoolean** [comment]
Regardless, I would recommend not using `static` but instead create 3 new keywords for each of static's behaviors:
```
#if !defined(internal)
#define internal static   /*used with a function*/
#endif
#define local_persist static   /*used with a local variable*/
#define global_variable static   /*used with a global variable*/ 

```
This way you can easily search your code for these keywords to find where they are being used.
example:
```
global_variable AwesomeVal = 7;

internal void 
DoSomethingAwesome(int SomeValue, float Percentage, custom_struct *CustomData)
{ 
      local_persist int Counter = AwesomeVal;
       /*more code*/
      Counter++;
}
```

**Comment by forslund** [comment]
@LongBoolean are you suggesting we use ```CamelCase``` for functions and ```underscore_separation``` for variables?

I have seen the second method of declaring functions in lwip and it is actually kind of great. You can search/grep for ```^FunctionName``` to find only the declaration of the function, makes life easy when you don't know the type it's supposed to return.

I'm not a tab-person myself but I can accept it if I must.

Maybe we can agree on line length of 80 chars atleast? =)

**Comment by LongBoolean** [comment]
When you are using tabs, a line length max of 80 would be a bit small because of indentation. Even when when using 4 spaces it's not hard to exceed 90. So I think the line length should be more of a guideline and less of a hard limit. You know on second thought lets go with 4 spaces. (I've been meaning to give that a try anyhow)

**Comment by LongBoolean** [comment]
just need to modify my vimrc

**Comment by LongBoolean** [comment]
Right now, mimic (the flite code) seems to use the style `underscore_separation` for functions and `noseporation` for variables. I am also seeing places where it uses `underscore_separation` for variables as well, but less frequently. I am not a fan of `noseporation`(unless it is a word like "webcam") as it is hard to read. I have seen other code bases use `CamelCase` for both functions and variables, while using `underscore_separation` for structs. example: `void DoStuff(foo_bar *FooBar)`
I'm not totally sure, it is nice for functions, variables, and structs to each have their own visual difference.  I do like the idea of using `CamelCase` for functions. Perhaps `CamelCase` for structs as well and `underscore_seporation` for variables?: `void DoStuff(FooBar *foo_bar)` 
What are your thoughts?

**Comment by forslund** [comment]
There are pros and cons for all approaches. I usually stick to either all camelCase or all underscore_separation, mixing tends to mess up my searches...

At the end of the day, it might be more important that we have a standard than what it is as long as we keep it consistent.

Maybe we should limit the first draft to just indentation and brace placement and keep using the variable/function naming scheme to what's in mimic right now?

**Comment by LongBoolean** [comment]
This may be a bit off topic, but is there any way that we can legally reduce the size of the licensing comment that is at the start of nearly every file. I still feel that a description of what is in that file should be there, as well as credit to the author. (should all contributors also have their name listed as well) Can we move the copy-write notice to another file (probably not), or move the notice to the bottom of the source file. Also they say this "2. Any modifications must be clearly marked as such." Does this mean that any modifications to the source code need to have a mark like `/*modified*/` attached to each line? Seems a bit strict doesn't it?

**Comment by LongBoolean** [comment]
And if that does mean that "any modification" needs to be clearly marked, and we do decide to change indentation and the way functions and vars are structured, then nearly every line would need to have that mark. lol anyone for writing mimic from scratch?

**Comment by zeehio** [comment]
I will agree to any code style standard you (@forslund @LongBoolean) decide.

Regarding license terms manipulation (moving, shortening...):
- I feel keeping copyright and license terms where they are is a sign of respect to flite developers.
- Copyright and license terms must be on each file because of `1. The code must retain the above copyright notice, this list of conditions and the following disclaimer.` It is not possible to point to another file.
- I am concerned that moving the copyright and license terms to the end of the file may be illegal (I am not a lawyer).

For these reasons I would not touch the file headers.


Regarding the "any modification should be marked as such" I can say:
- All the modifications are clearly marked as such in the git repository. Anyone can get the original Flite from the [initial commit](https://github.com/MycroftAI/mimic/tree/3bb10f78fdc3f94a0fbaf8a1c3830c8e54d6c517) and the diff to the latest development version.
- By renaming our flite fork to mimic, we are clearly marking that the whole code has modifications all over the place. I therefore think we comply with the terms.
- The plausible intention of the clause was to prevent that flite devs get bug reports for things they did not code. With mimic this seems clear to me.

**Comment by forslund** [comment]
I agree with @zeehio, the git history should be enough to mark any modification. I'm not bothered by the file headers, I think we can keep them as they are.

I'll see if I can find the correct indent (great program, I did not know about it earlier! Thanks) settings and do a short write up on the code style tonight or during the weekend.

**Comment by LongBoolean** [comment]
ok, just wondering what you guys thought.

**Comment by forslund** [comment]
Seems like
```indent audio.c -i4 -bl -npsl -brs -bli0 -nut -o audio_i.c```

is what we have described.

this turns code like
```
static void audio_write_buffer(cst_audiodev *ad, void *buff,
                               int num_samples, int num_channels) {
        int n, r, i;
  int num_shorts = num_samples*num_channels;
  int bytes_per_short = audio_bps(ad->fmt);
  int num_bytes = num_shorts*bytes_per_short;
  if (CST_AUDIOBUFFSIZE <= 0) {
    r = audio_write(ad, buff, num_bytes);
    if (r <= 0) {
      cst_errmsg("failed to write %d samples\n", num_shorts);
    }
  } else {
[...]
}
```
into
```
static void audio_write_buffer (cst_audiodev * ad, void *buff,
                                int num_samples, int num_channels)
{
    int n, r, i;
    int num_shorts = num_samples * num_channels;
    int bytes_per_short = audio_bps (ad->fmt);
    int num_bytes = num_shorts * bytes_per_short;
    if (CST_AUDIOBUFFSIZE <= 0)
    {
        r = audio_write (ad, buff, num_bytes);
        if (r <= 0)
        {
            cst_errmsg ("failed to write %d samples\n", num_shorts);
        }
    }
    else
    {
[...]
}
```

@LongBoolean should we go for the line break between function type and function name?

If there's no objection to this I'll add the coding standard to the readme and create a pull request.

**Comment by zeehio** [comment]
Cool! These days that the only pull request pending does not change any .c or .h code is the best moment to improve indentation :-)

**Comment by LongBoolean** [comment]
@forslund Sorry for not getting back to you sooner.(I was away from a computer for the weekend) 
I would say to go ahead with the line break between function type and function name.(if that is something you guys want.) It does have several benefits when it comes to readability of source code. One of the drawbacks I suppose is that some editors expect it on one line and get confused. My current vim setup inserts another tab (when doing `=G`) where there shouldn't be one:
```
    void
foo()
{
    /*code*/
}
```
I'm currently looking into how to fix this.

**Comment by LongBoolean** [comment]
I have found the solution: http://stackoverflow.com/questions/28217118/vim-indents-c-c-functions-badly-when-the-type-and-name-are-in-different-lines

**Comment by LongBoolean** [comment]
Apparently indenting the function type on the line above the function name is yet another convention some choose.(and another is indenting twice) Although I don't know why that is vim's default behavior.

**Comment by zeehio** [comment]
I believe this can be closed thanks to pull request #28.

Feel free to reopen in case you feel I'm mistaken :smile:

**Comment by LongBoolean** [comment]
@forslund 
I noticed the switch statement guidelines in the readme. We talked about where the break should be (in or out of curly braces), but we didn't really go over what indentation standard to use for switch statements.

Indentation currently in the readme:
```
switch(state)
{
case 1:     /* side note:  vim, and quite a few other editors, default to indenting this*/
   doA(1);
   break;
case 2:
   {
      int b = 2;
      doA(b);
   }
   break;
case 3:
[...]
}
```
The above leaves out a few cases :)

Another indentation proposal:
```
switch(state)
{
    case 1:
    {                   /* even if the case only has one line, use curly braces (similar reasoning as with if's) */ 
        doA(1);
    } break;
                        /* separate cases with a line */
    case 2:        /* unless it falls into the next one */
    case 3:
    {
        DoThisFirst();
    }                /* no break, this one also falls through */
    case 4:
    {                  /* notice that curly braces line up with 'case' on line above */
        int b = 2;
        doA(b);
    } break;     /* putting 'break' on this line saves some room and makes it look a little nicer */

    case 5:
    {
        /* more code */
    }
                    
    default:      /* It is nice to always have a default case, even if it does nothing */
    {
        InvalidDefaultCase(); /* or whatever, it depends on what you are trying to do. */
    }
    /* in practice it might be a good Idea to use macros for commonly used default cases 
       so instead of having the default case above you could replace it with this: */
    InvalidDefaultCase; /* and have a macro for it of coarse */ 
}
```

**Comment by forslund** [comment]
I entered the the format that the indent-command already had produced for simplicity. If you feel strongly about this feel free to update the coding style and the source code accordingly.

(I usually leave out the braces when they aren't needed to make the code easier to read. I don't feel very strongly about it so I'll defer to your opinion.)

**Comment by LongBoolean** [comment]
Ok, I just wanted to get your thoughts on it before making any changes. I will modify the readme to reflect what I stated above. (feel free to chime in if any of you have any further thoughts on the matter) I think most of the changes I listed above will need to be made by hand when they are encountered. I don't think it is necessary that everything match the guidelines exactly right this moment. 

And again it kind of comes down to personal taste and the coding style you are accustom to, as to what is easier and what is harder to read. I like to include curly braces all the time because when I am scanning over the code there is only one way to write an if/case/switch/for. Also it decreases the chances that I or someone else will accidentally modify the control flow in an incorrect way, if the braces are already there.

**Comment by forslund** [comment]
I think last addition to the README by @LongBoolean fixes this last part. Can we close the issue?

**Comment by LongBoolean** [comment]
I'm ok with it, if in the future some more things need to be added/changed we can always open up a new issue.

**Comment by forslund** [comment]
@LongBoolean, I like the way you think! Closing
